HOST_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode

  API_TYPE: "azure_ad" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://cloudgpt-openai.azure-api.net/", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  API_KEY: "YOUR_KEY",  # The OpenAI API key
  API_VERSION: "2024-04-01-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4o-20240513",  #"gpt-4o-mini-20240718", #"gpt-4o-20240513",  # The only OpenAI model by now that accepts visual input

  # API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  # API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  # API_KEY: "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",  # The OpenAI API key
  # API_VERSION: "2024-02-15-preview", # "2024-02-15-preview" by default
  # API_MODEL: "gpt-4-vision-preview",  # The only OpenAI model by now that accepts visual input

  ###For the AOAI
  # API_DEPLOYMENT_ID: "gpt-4-visual-preview", # The deployment id for the AOAI API
  ### For Azure_AD
  AAD_TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47", # Set the value to your tenant id for the llm model
  AAD_API_SCOPE: "openai", # Set the value to your scope for the llm model
  AAD_API_SCOPE_BASE: "feb7b661-cac7-44a8-8dc1-163b63c23df2"  # Set the value to your scope base for the llm model, whose format is API://YOUR_SCOPE_BASE, and the only need is the YOUR_SCOPE_BASE
}

APP_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode

  API_TYPE: "azure_ad" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://cloudgpt-openai.azure-api.net/", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  API_KEY: "YOUR_KEY",  # The OpenAI API key
  API_VERSION: "2024-04-01-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4o-20240513",  #"gpt-4o-mini-20240718", # "gpt-4o-20240513",  # The only OpenAI model by now that accepts visual input
  # API_MODEL: "gpt-4o-mini-20240718",  #"gpt-4o-mini-20240718", # "gpt-4o-20240513",  # The only OpenAI model by now that accepts visual input

  # API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  # API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  # API_KEY: "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",  # The OpenAI API key
  # API_VERSION: "2024-02-15-preview", # "2024-02-15-preview" by default
  # API_MODEL: "gpt-4-vision-preview",  # The only OpenAI model by now that accepts visual input

  # API_TYPE: "aoai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  # API_BASE: "YOUR_ENDPOINT", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  # API_KEY: "YOUR_KEY",  # The OpenAI API key
  # API_VERSION: "2023-12-01-preview" ,# "2024-02-15-preview" by default
  # API_MODEL: "YOUR_MODEL",  # The only OpenAI model by now that accepts visual input

  ###For the AOAI
  # API_DEPLOYMENT_ID: "gpt-4-visual-preview", # The deployment id for the AOAI API
  ### For Azure_AD
  AAD_TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47", # Set the value to your tenant id for the llm model
  AAD_API_SCOPE: "openai", # Set the value to your scope for the llm model
  AAD_API_SCOPE_BASE: "feb7b661-cac7-44a8-8dc1-163b63c23df2"  # Set the value to your scope base for the llm model, whose format is API://YOUR_SCOPE_BASE, and the only need is the YOUR_SCOPE_BASE

}

BACKUP_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode
  API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  API_KEY: "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",  # The OpenAI API key
  API_VERSION: "2024-02-15-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4-vision-preview",  # The only OpenAI model by now that accepts visual input

  # API_TYPE: "aoai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  # API_BASE: "YOUR_ENDPOINT", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API. As for the AAD, it should be your endpoints.
  # API_KEY: "YOUR_KEY",  # The OpenAI API key
  # API_VERSION: "2023-12-01-preview" ,# "2024-02-15-preview" by default
  # API_MODEL: "YOUR_MODEL",  # The only OpenAI model by now that accepts visual input

  ###For the AOAI
  API_DEPLOYMENT_ID: "gpt-4-visual-preview", # The deployment id for the AOAI API
  ### For Azure_AD
  AAD_TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47", # Set the value to your tenant id for the llm model
  AAD_API_SCOPE: "openai", # Set the value to your scope for the llm model
  AAD_API_SCOPE_BASE: "feb7b661-cac7-44a8-8dc1-163b63c23df2"  # Set the value to your scope base for the llm model, whose format is API://YOUR_SCOPE_BASE, and the only need is the YOUR_SCOPE_BASE
}


### For parameters
MAX_TOKENS: 2000  # The max token limit for the response completion
MAX_RETRY: 3  # The max retry limit for the response completion
TEMPERATURE: 0.0  # The temperature of the model: the lower the value, the more consistent the output of the model
TOP_P: 0.0  # The top_p of the model: the lower the value, the more conservative the output of the model
TIMEOUT: 60  # The call timeout(s), default is 1 mins

### For RAG

## RAG Configuration for the offline docs
RAG_OFFLINE_DOCS: False  # Whether to use the offline RAG.
RAG_OFFLINE_DOCS_RETRIEVED_TOPK: 1  # The topk for the offline retrieved documents

## RAG Configuration for the Bing search
BING_API_KEY: "a5f1dec156334648a2354fabb221ffff"  # The Bing search API key
RAG_ONLINE_SEARCH: False  # Whether to use the online search for the RAG.
RAG_ONLINE_SEARCH_TOPK: 5  # The topk for the online search
RAG_ONLINE_RETRIEVED_TOPK: 1 # The topk for the online retrieved documents

## RAG Configuration for experience
RAG_EXPERIENCE: False  # Whether to use the offline RAG.
RAG_EXPERIENCE_RETRIEVED_TOPK: 5  # The topk for the offline retrieved documents


## RAG Configuration for demonstration
RAG_DEMONSTRATION: False  # Whether to use the RAG from its user demonstration.
RAG_DEMONSTRATION_RETRIEVED_TOPK: 5  # The topk for the offline retrieved documents
RAG_DEMONSTRATION_COMPLETION_N: 3  # The number of completion choices for the demonstration result





